### PR TITLE
Better organized navigation by renaming files and directories

### PR DESCRIPTION
**Pull request by Delivator**
- Better navigation and page url by changing a lot of paths in the docs folder
- Updated some titles
- Changed all external links to open in a new tab
- Added a screenshot to the explorer page
- Some more minor changes

### CODE REVIEW

**Comment by Delivator** [comment]
Before:
o2B6EQ1XtV

After:
msedge_CszLllTrpA

**Comment by Delivator** [comment]
Also replaced youtube links with embeds
image

**Comment by DangerCZ** [comment]
Buiding with Skynet would make more sense under Skynet rather than Discover, right?

**Comment by Delivator** [comment]
> Buiding with Skynet would make more sense under Skynet rather than Discover, right?

Done

**Review by DangerCZ — APPROVED** [review]

**Pull request merged**
