### PR TITLE
lithuanian translation #1

### PR DESCRIPTION
**Pull request by ceolorenso**
gotta do more in future

### CODE REVIEW

**Comment by Delivator** [comment]
Do you want me to merge this or do you want to add more changes to that commit?
You can always create a new PR if you want to add more changes!

**Comment by ceolorenso** [comment]
> Do you want me to merge this or do you want to add more changes to that commit?
> You can always create a new PR if you want to add more changes!

Sure. You can merge it. Also I've missed to build mkdocs.. Just fixed it.

**Comment by Delivator** [comment]
Oh okay so it is "Lietuvių" and not "Lietuvis", thanks for the edit!

**Comment by Delivator** [comment]
For some reason the build fails.
I don't know why yet. Let my try to fix it and then I'll merge.

**Comment by Delivator** [comment]
Heck yeah working now

**Pull request merged**
