### PR TITLE
Add i18n plugin to support multiple languages

### PR DESCRIPTION
**Pull request by Delivator**
Adds the mkdocs [mkdocs-static-i18n](https://github.com/ultrabug/mkdocs-static-i18n) plugin

### CODE REVIEW

**Comment by Delivator** [comment]
Working with auto generated nav
https://0g04ar8cfkk6qgutk38heicq6i2o09a64f3j33j0c0u1euorl5hg1oo.siasky.net/

**Comment by lukehmcc** [comment]
Since this directly clashes with pr20(my bad on that sorry) I'm gonna move all the "new" articles(so all of the articles from the branch `navigation-fix-1` into their new locations on this branch. That should fix all the conflicts. 

Unfortunately I haven't figured out a way, with the autogenerated nav, to not have that annoying sub-folder dropdown thing, so if anyone has ideas on that I'd appreciate it.

**Comment by lukehmcc** [comment]
I'm gonna merge this via the command line because it's being annoying

**Comment by lukehmcc** [comment]
merging this
I'll have to address the annoying drop down thing later

**Pull request merged**
